# code: language=ansible
---
- name: Update All
  hosts: all
  gather_facts: true
  roles:
    - role: update_packages
      become: true

- name: K3S
  hosts: k3s
  gather_facts: true
  roles:
    - role: k3s
      become: true

- name: Install Docker and Form Docker Swarm
  hosts: docker
  gather_facts: true
  roles:
    - role: docker
      become: true
    - role: swarm

- name: Install qemu-guest-agent
  hosts: proxmox
  gather_facts: true
  roles:
    - role: qemu-guest-agent
      become: true

- name: Restart Elastic Agent
  hosts: proxmox
  gather_facts: true
  roles:
    - role: restart-elastic-agent
      become: true

- name: Install Wireguard
  hosts: wireguard
  gather_facts: true
  roles:
    - role: wireguard
      become: true
- name: Install and Start Cloudflare Tunnel
  hosts: tunnel_hosts
  gather_facts: true
  roles:
    - role: docker
      become: true
    - role: cf_tunnel

- name: Install Tor and Setup Tor Exit Node
  hosts: tor_exit
  gather_facts: true
  roles:
    - role: tor
      become: true

- name: Install and Start Minio
  hosts: local_swarm_w_high
  gather_facts: true
  roles:
    - role: docker
      become: true
    - role: minio
