# code: language=ansible
- name: Debug
  hosts: all
  gather_facts: yes
  tasks:
    # - name: Print initial master ip
    #   ansible.builtin.debug:
    #     var: hostvars['k3s-m1']['ansible_default_ipv4']['address']

    # - name: Print all host default ipv4
    #   ansible.builtin.debug:
    #     var: hostvars[ansible_host]['ansible_default_ipv4']['address']
    #   when: node_type | default('undefined') == 'master'

    # - name: Test set fact
    #   ansible.builtin.set_fact:
    #     master_ip: "{{ hostvars['k3s-m1']['ansible_default_ipv4']['address'] }}"

    # - name: Print master ip
    #   ansible.builtin.debug:
    #     var: master_ip

    - name: Check if K3S is already installed
      ansible.builtin.shell:
        cmd: 'test -f /usr/local/bin/k3s'
      register: k3s_installed
      failed_when: false

    - name: Print k3s_installed
      ansible.builtin.debug:
        var: k3s_installed.rc
