# code: language=ansible
---
- name: Install qemu-guest-agent
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - qemu-guest-agent
    state: present

- name: Enable qemu-guest-agent
  ansible.builtin.service:
    name: qemu-guest-agent
    enabled: true
    state: started
