# code: language=ansible
---
- name: Install prerequisites
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - apt-transport-https
    state: present

- name: Add Tor's official GPG key
  ansible.builtin.apt_key:
    url: 'https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc'
    keyring: /usr/share/keyrings/tor-archive-keyring.gpg
    state: present

- name: Add Tor's official apt repository
  ansible.builtin.apt_repository:
    update_cache: true
    filename: tor
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/tor-archive-keyring.gpg] https://deb.torproject.org/torproject.org {{ ansible_distribution_release }} main'
    state: present

- name: Add Tor's official apt source repository
  ansible.builtin.apt_repository:
    update_cache: true
    filename: tor
    repo: 'deb-src [arch=amd64 signed-by=/usr/share/keyrings/tor-archive-keyring.gpg] https://deb.torproject.org/torproject.org {{ ansible_distribution_release }} main'
    state: present

- name: Install tor, nyx, and debian keyring
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - tor
      - deb.torproject.org-keyring
    state: present

- name: Copy Tor Exit Notice Page
  ansible.builtin.copy:
    src: tor-exit-notice.html
    dest: /etc/tor/tor-exit-notice.html
    owner: debian-tor
    group: debian-tor
    mode: '0644'

- name: Create Directories for Tor Exit Node 1 and 2
  ansible.builtin.file:
    path: '/etc/tor/{{ item }}'
    state: directory
    owner: debian-tor
    group: debian-tor
    mode: '0755'
  loop:
    - /node1
    - /node2

- name: Create Log Files for Tor Exit Node 1 and 2
  ansible.builtin.file:
    path: '/etc/tor/{{ item }}'
    state: touch
    owner: debian-tor
    group: debian-tor
    mode: '0644'
    modification_time: preserve
    access_time: preserve
  loop:
    - /node1/notices.log
    - /node2/notices.log

- name: Configure Tor Node 1
  ansible.builtin.template:
    src: torrc.j2
    dest: /etc/tor/node1/torrc
    owner: debian-tor
    group: debian-tor
    mode: '0644'
