# code: language=ansible
---
- name: Pull Minio Image
  ansible.builtin.command:
    cmd: docker pull quay.io/minio/minio
  changed_when: false

- name: Import Minio Secrets
  ansible.builtin.include_vars:
    file: secrets.yml.vault
